### ISSUE TITLE
App crashes immediately after I enter phone number

### ISSUE THREAD

**Issue by amrhosseiny** [rusq/wipemychat#11]
The title is pretty much it. The app crashes immediately after I enter my phone number. Windows 10. And I use  wipemychat_Windows_x86_64.zip, Nov 25 2023.

**Comment by rusq** [comment]
Hey @amrhosseiny, were there any messages printed?

**Comment by rusq** [comment]
Just tried the aforementioned version on windows, and it works on my machine, looking forward to see the error message.

**Comment by amrhosseiny** [comment]
Hey there, 
I checked again, the problem persists. And no there was not any messages printed. Only a sudden crash after I enter the phone number...

**Comment by rusq** [comment]
My guess is - you have entered invalid api hash or api secret or both, I just tried it, with invalid values, it allows to enter the phone number, but then terminates.  I'll see if there's an API endpoint that allows to check the validness of api credentials before offering to enter the phone number.

Can you reset the auth with `.\wipemychat -reset` and try again, ensuring that credentials are correct?

**Comment by exciar** [comment]
this is the same issue that I had been dealing with I'm going to try resetting and see if it makes a difference

**Comment by exciar** [comment]
@amrhosseiny @rusq  I have a suggestion and I think I know why this is happening and yes I think there needs to be a menu

it needs to state explicitly in the enter a phone number part (after credentials) that its the **International Number format**

**Comment by amrhosseiny** [comment]
Hi again...
I've checked both possibilities before posting this issue. I am sure that 1. I am entering the phone number with correct formatting and 2. the api credentials entered are correct. I don't know what else could be wrong...

**Comment by exciar** [comment]
> Hi again... I've checked both possibilities before posting this issue. I am sure that 1. I am entering the phone number with correct formatting and 2. the api credentials entered are correct. I don't know what else could be wrong...

run the reset like how rusq instructed me how and then, rerun the program if it closes when it prompts you to enter a phone number (international format) then run the number again (international format)

**Comment by rusq** [comment]
@exciar that's a good suggestion re adding instructions on international number format, thanks!  I'll bundle it with the tracing

**Comment by rusq** [comment]
@amrhosseiny @exciar I'm glad that finally this repository gets some activity, so thank you both for issues and suggestions.   I haven't advertised it anywhere, so that got me wondering, could you tell me how you discovered this repository?

**Comment by amrhosseiny** [comment]
@rusq 
Also I found it using github search :) Nice work, by the way...

**Comment by amrhosseiny** [comment]
@rusq 
I got a new api_id and api_hash and that fixed the problem! don't know what was wrong with the first one...
Thanks...
Just one more thing, could you please add support for arabic/persian characters? Group names with those characters aren't shown properly...Since that's out of the scope of this issue(?) I can open a new one, if you like...

**Comment by rusq** [comment]
Glad to hear that it started working for you!

I created an issue #13 , but it may be harder than it seems, as this might be limitation of the tview library - I'll have to explore it a bit.

You could use the "batch" mode as a workaround meanwhile, it will use your terminal capabilities, and output proper UTF-8.

**Comment by rusq** [comment]
This is now fixed, it won't save creds unless they're valid.

Also, it won't allow to enter the phone in non-international format (the checks are pretty dumb, no check for the phone number length, but that's on the user).
