### ISSUE TITLE
Do not save credentials if they're invalid

### ISSUE THREAD

**Issue by greysian777** [rusq/wipemychat#8]
2024/01/24 20:29:06 auth flow: send code: send code: rpcDoRequest: rpc error code 400: API_ID_INVALID

I got this error, I put API id and hash as it on my.telegram.org, how to delete cache so I can put API id again?

**Comment by rusq** [comment]
Hey, hey!

Have you tried running `wipemychat -h` to see the help screen?

The flag you're after is `-reset`

```
wipemychat -reset
```

**Comment by rusq** [comment]
But good call, probably I need to update it not to save the credentials if they're invalid.

**Comment by rusq** [comment]
See also #9
